// Generate the web app's ABI from the compiled artifact, so the two can never drift.
import { readFileSync, writeFileSync } from 'node:fs'
const artifact = JSON.parse(
  readFileSync('contracts/artifacts/contracts/FolioVault.sol/FolioVault.json', 'utf8'),
)
const out = `// GENERATED by scripts/emit-abi.mjs from contracts/artifacts. Do not edit by hand.
export const folioVaultAbi = ${JSON.stringify(artifact.abi, null, 2)} as const
`
writeFileSync('web/lib/vault-abi.ts', out)
console.log(`wrote web/lib/vault-abi.ts (${artifact.abi.length} entries)`)
